### ISSUE TITLE
php7 scalar type hints problem

### ISSUE THREAD

**Issue by apgubarev** [yiisoft/yii2-apidoc#35] opened 2016-01-16 10:20 UTC
For example:

``` php
class {
    public static function cacheGetTime() :  int
    {
        return 3600;
    }
}
```

And that file is no apidoc generation. Problem in ": int" because without him all work

**Comment by cebe** [comment] 2016-11-22 13:55
duplicate of #8

**Closed by cebe** 2016-11-22 13:55 UTC
Labels: enhancement
