### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2-apidoc#60] opened 2016-03-12 22:24 UTC
Hello. Maybe i doing something wrong but i have issue with composer version

```
  Problem 1
    - cebe/markdown-latex 1.0.0 requires cebe/markdown ~1.0.0 -> no matching package found.
    - yiisoft/yii2-apidoc 2.0.4 requires cebe/markdown-latex ~1.0.0 -> satisfiable by cebe/markdown-latex[1.0.0].
    - Installation request for yiisoft/yii2-apidoc 2.0.4 -> satisfiable by yiisoft/yii2-apidoc[2.0.4].
```
```
  "require": {
    "fxp/composer-asset-plugin": "v1.1.2",
    "yiisoft/yii2": "2.0.7",
    "yiisoft/yii2-debug": "2.0.5",
    "yiisoft/yii2-gii": "2.0.4",
    "cebe/markdown": "1.1.0",
    "yiisoft/yii2-apidoc": "2.0.4"
  }
```

**Comment by cebe** [comment] 2016-03-17 04:28
duplicate of #24

**Closed by cebe** 2016-03-17 04:28 UTC
