### ISSUE TITLE
Error - Rendering files: 0% (0/375) ETA: n/a   Error:

### ISSUE THREAD

**Issue by alex290** [yiisoft/yii2-apidoc#156] opened 2017-11-19 12:02 UTC
### What steps will reproduce the problem?
.\vendor\bin\apidoc api vendor\yiisoft\yii2 yii2-docs

ERROR

Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
374 files to update.
Processing files... done.
Updating cross references and backlinks... done.
**Rendering files: 0% (0/375) ETA: n/a   Error: The file or directory to be published does not exist: D:\OSPanel\domains\yii2\vendor\yiisoft\yii2-apidoc/../..\bower/bootstrap/dist**

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.13.1
| PHP version      |7.1
| Operating system |Windows

**Comment by cebe** [comment] 2017-11-20 08:42
duplicate of #152

**Closed by cebe** 2017-11-20 08:42 UTC
