### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by drutalj** [yiisoft/yii2-apidoc#166] opened 2018-04-20 19:52 UTC
### What steps will reproduce the problem?
```
# composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application
# cd yii-application
# composer require --prefer-dist yiisoft/yii2-apidoc
```

### What do you get instead?
```
Using version ^2.1 for yiisoft/yii2-apidoc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yiisoft/yii2-apidoc ^2.1 -> satisfiable by yiisoft/yii2-apidoc[2.1.0].
    - Conclusion: remove cebe/markdown 1.1.2
    - Conclusion: don't install cebe/markdown 1.1.2
    - yiisoft/yii2-apidoc 2.1.0 requires cebe/markdown-latex ~1.0 -> satisfiable by cebe/markdown-latex[1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4].
    - cebe/markdown-latex 1.0.0 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.0 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.1 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.2 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.3 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - cebe/markdown-latex 1.1.4 requires cebe/markdown ~1.0.0 -> satisfiable by cebe/markdown[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - Can only install one of: cebe/markdown[1.0.0, 1.1.2].
    - Can only install one of: cebe/markdown[1.0.1, 1.1.2].
    - Can only install one of: cebe/markdown[1.0.2, 1.1.2].
    - Can only install one of: cebe/markdown[1.0.3, 1.1.2].
    - Installation request for cebe/markdown (locked at 1.1.2) -> satisfiable by cebe/markdown[1.1.2].


Installation failed, reverting ./composer.json to its original content.
```

### Additional info

| Q                  | A
| ------------------ | ---
| Yii vesion         | 2.0.15.1
| Yii APIDoc version |  2.1.0
| PHP version        | 5.6.33
| Operating system   | Debian 8

**Comment by schmunk42** [comment] 2018-04-23 05:47
Duplicate of https://github.com/yiisoft/yii2-apidoc/issues/123

**Closed by schmunk42** 2018-04-23 05:47 UTC
