### ISSUE TITLE
@inheritdoc not working

### ISSUE THREAD

**Issue by neoacevedo** [yiisoft/yii2-apidoc#194] opened 2020-04-23 18:57 UTC
{@inheritdoc} is not pulling the documentation for classes, methods and properties.

`{@inheritDoc}` is rendered as plain text, meaning that in the documentation, it will have the literal `{@inheritDoc}` instead of, at least, the same current non-doc as in {@inheritdoc}

**Comment by atangemann** [comment] 2020-05-10 21:18
I encountered the same problem. Let me explain this in detail:
When I try to create the api documentation, I issue this command:
`vendor/bin/apidoc api "api/modules,frontend/controllers,frontend/models,common/controllers,common/models" public --exclude="vendor/"`
Then the documentation is created, but the {inheritdoc} comments are missing.
![image](https://user-images.githubusercontent.com/41471916/81510596-2ef9b580-9313-11ea-92d1-790a9480b924.png)

When I include the yii framework, I issue this command:
`vendor/bin/apidoc api "api/modules,frontend/controllers,frontend/models,common/controllers,common/models,vendor/yiisoft/yii2/" public --exclude="vendor/"`
Then the {inheritdoc} comments are filled, but looking at the index.html file will only show yii classes.
![image](https://user-images.githubusercontent.com/41471916/81510643-acbdc100-9313-11ea-8a04-0c90fc44b33c.png)
I can search for my classes but they are not shown in the list to the left of the index.html file.
Additionally all the documentation files for the yii framework are created, which is not necessary.
I think the OP has the same problem.

**Comment by neoacevedo** [comment] 2020-11-18 17:56
All the documentation for the yii framework is generated because you have specified it in the api parameter:
> vendor/bin/apidoc api "api/modules,frontend/controllers,frontend/models,common/controllers,common/models,**vendor/yiisoft/yii2/**" public --exclude="vendor/".

**Comment by neoacevedo** [comment] 2020-11-19 15:37
Another issue for `@inheritdoc` is related to the following error:

`Method tableName|attributeLabels|behaviors has no parent to inherit from in namespace\models\ModelFile.`. It's applied to any class who sets the inhertdoc in the docblock.

**Comment by atangemann** [comment] 2020-11-19 19:11
I have to specify "vendor/yiisoft/yii2" because the @inheritdocs comments would be missing otherwise. See my example above.
> All the documentation for the yii framework is generated because you have specified it in the api parameter:

**Comment by arogachev** [comment] 2021-12-06 11:48
If you mean different variations, seems like it was fixed in #218. I did a retest and all 4 variations:

- `@inheritdoc`
- `@inheritDoc`
- `{@inheritdoc}`
- `{@inheritDoc}`

work as expected for methods. But for properties the description is empty. Will investigate it further.

**Comment by arogachev** [comment] 2021-12-07 06:15
> https://github.com/yiisoft/yii2-apidoc/issues/194#issue-605780903
So for methods and properties I can't reproduce initial issue with the latest master. For classes `@inheritdoc` indeed is not supported, I created a new issue - #246. As I wrote there, this seems to be a rare case, so it won't be implemented right away.

> https://github.com/yiisoft/yii2-apidoc/issues/194#issuecomment-626391256
As for generating docs for a user project, seems to be a duplicate of #49 and #131.

> https://github.com/yiisoft/yii2-apidoc/issues/194#issuecomment-730456266
Please provide a minimal snippet to reproduce the problem. Also for `@see` tag a new issue is probably needed.

**Comment by arogachev** [comment] 2021-12-07 06:16
Closing this one. Feel free to reopen with more info / snippets.

**Comment by neoacevedo** [comment] 2021-12-07 14:40
> > [#194 (comment)](https://github.com/yiisoft/yii2-apidoc/issues/194#issue-605780903)
> > [#194 (comment)](https://github.com/yiisoft/yii2-apidoc/issues/194#issuecomment-730456266)
> 
> Please provide a minimal snippet to reproduce the problem. Also for `@see` tag a new issue is probably needed.

Since it comes from last year, I forgot to mention it is solved, not else, for me, the inheritdoc tag.

**Comment by samdark** [comment] 2021-12-08 07:56
Please check master.

**Comment by arogachev** [comment] 2021-12-09 10:30
@samdark It should work on 2.1.6 too. 

@neoacevedo Please provide more relevant code, I still can't reproduce the issue.

For `yii\rest\Controller` as you can see it works for both properties and methods:

- https://www.yiiframework.com/doc/api/2.0/yii-rest-controller#$enableCsrfValidation-detail (can't find `$modelClass` neither in web nor rest controller).
- https://www.yiiframework.com/doc/api/2.0/yii-base-component#behaviors()-detail.

**Comment by neoacevedo** [comment] 2021-12-09 18:04
For `$modelClass` attribute, you are checking the incorrect class, it is in [ActiveController](https://www.yiiframework.com/doc/api/2.0/yii-rest-activecontroller#$modelClass-detail) class.

And, as I post before, the `@inheritdoc` isn't working yet at least, for me.

The command I run to render the documentation is:
```sh
php .\vendor\bin\apidoc api . /path/to/my-project/apidoc --interactive=0 --excludes="vendor" --page-title="My Project - Documentación"
```

In my composer, I have in the _require_dev_ section: 
```js
    "require-dev": {
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/specify": "~0.4.6",
        "symfony/browser-kit": ">=2.7 <=4.2.4",
        "yiisoft/yii2-apidoc": "~2.1.0"
    },
```
And inside the composer.lock file I have the version 2.1.6:

```js
{
            "name": "yiisoft/yii2-apidoc",
            "version": "2.1.6",
            "source": {
                "type": "git",
                "url": "https://github.com/yiisoft/yii2-apidoc.git",
                "reference": "815b39a5c8429829ec52948237754c6bf4396d0c"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/yiisoft/yii2-apidoc/zipball/815b39a5c8429829ec52948237754c6bf4396d0c",
                "reference": "815b39a5c8429829ec52948237754c6bf4396d0c",
                "shasum": ""
            },
            "require": {
                "cebe/js-search": "~0.9.3",
                "cebe/markdown": "~1.0.0 | ~1.1.0 | ~1.2.0",
                "cebe/markdown-latex": "~1.0",
                "nikic/php-parser": "^1.0",
                "php": ">=5.4",
                "phpdocumentor/reflection": "^3.0.1",
                "phpdocumentor/reflection-docblock": "^2.0.4",
                "scrivo/highlight.php": "~9.13",
                "yiisoft/yii2": "~2.0.13",
                "yiisoft/yii2-bootstrap": "~2.0.0"
            },
            "require-dev": {
                "cweagans/composer-patches": "^1.7",
                "phpunit/phpunit": "4.8.34"
            },
            "bin": [
                "apidoc"
            ],
            "type": "yii2-extension",
            "extra": {
                "branch-alias": {
                    "dev-master": "2.1.x-dev"
                },
                "composer-exit-on-patch-failure": true,
                "patches": {
                    "phpunit/phpunit-mock-objects": {
                        "Fix PHP 7 and 8 compatibility": "https://yiisoft.github.io/phpunit-patches/phpunit_mock_objects.patch"
                    },
                    "phpunit/phpunit": {
                        "Fix PHP 7 compatibility": "https://yiisoft.github.io/phpunit-patches/phpunit_php7.patch",
                        "Fix PHP 8 compatibility": "https://yiisoft.github.io/phpunit-patches/phpunit_php8.patch"
                    }
                }
            },
            "autoload": {
                "psr-4": {
                    "yii\\apidoc\\": ""
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "BSD-3-Clause"
            ],
            "authors": [
                {
                    "name": "Carsten Brandt",
                    "email": "mail@cebe.cc"
                }
            ],
            "description": "API Documentation generator for the Yii framework 2.0",
            "keywords": [
                "api",
                "apidoc",
                "documentation",
                "phpdoc",
                "yii2"
            ],
            "support": {
                "forum": "http://www.yiiframework.com/forum/",
                "irc": "irc://irc.freenode.net/yii",
                "issues": "https://github.com/yiisoft/yii2-apidoc/issues",
                "source": "https://github.com/yiisoft/yii2-apidoc",
                "wiki": "http://www.yiiframework.com/wiki/"
            },
            "funding": [
                {
                    "url": "https://github.com/yiisoft",
                    "type": "github"
                },
                {
                    "url": "https://opencollective.com/yiisoft",
                    "type": "open_collective"
                },
                {
                    "url": "https://tidelift.com/funding/github/packagist/yiisoft/yii2-apidoc",
                    "type": "tidelift"
                }
            ],
            "time": "2021-05-05T21:43:18+00:00"
},
```

The minimum stability in my composer file is in _stable_. 

The image for the `behavior` method comes from my controller who extends `\yii\rest\ActiveController`, which extends from `\yii\base\Component`:

```php
class ApiController extends \yii\rest\ActiveController
{
    /** {@inheritdoc} */
    public $modelClass = 'app\models\User';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator']['formats']['application/json'] = Response::FORMAT_JSON;
        return $behaviors;
    }
...
}
```
But I get the same result for any other controller:

```php
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'access' => [
                    'class' => AccessControl::class,
                    'rules' => [
                        [
                            'allow' => true,
                            'roles' => ['@'],
                        ],
                    ],
                ],
                'verbs' => [
                    'class' => VerbFilter::class,
                    'actions' => [
                        'delete' => ['GET'],
                    ],
                ],
            ]
        );
    }
...
}
```
![imagen](https://user-images.githubusercontent.com/438372/145448146-5964fb73-7e0a-4775-926d-441bf3bc69bf.png)

I don't have a clue what more code may I provide here, but my guess about this issue is about the nested inheritance, because I have found for each controller: `Method behaviors has no parent to inherit from in [controller name].`, so I think this tag can only render the first level on inheritance.

**Comment by arogachev** [comment] 2021-12-10 11:04
@neoacevedo Sorry, my bad. Yes, it only works correctly if a closest parent has actual description (for methods at least).

**Comment by arogachev** [comment] 2021-12-10 11:05
I'll move it to a new issue.

**Closed by arogachev** 2021-12-10 11:05 UTC
Labels: type:bug
