### ISSUE TITLE
Composer conflict with AspectMock 2.0

### ISSUE THREAD

**Issue by Ni-san** [yiisoft/yii2-apidoc#74] opened 2016-06-24 07:03 UTC
### What steps will reproduce the problem?

Upgrade Codeception/AspectMock up to v2
### What do you get instead?

AspectMock requires "nikic/php-parser": "^1.2|^2.0" (via goaop/framework > goaop/parser-reflection)
yii2-apidoc requires "nikic/php-parser": "0.9.*"

It is problem since old version of AspectMock can't work with some php5.6/php7 features.

What about upgrade up to php-parser 2.0?
### Additional info

| Q | A |
| --- | --- |
| Yii vesion | 2.0.8 |
| PHP version | 7.0.7 |
| Operating system | GNU/Linux 3.16.0-38-generic (Linux Mint) |

**Comment by kaiserfedor** [comment] 2016-07-11 10:13
@cebe Hello, I have the same problem. What do you think about upgrade?

**Comment by cebe** [comment] 2016-07-11 10:21
I am for doing that but I do not have time to do it soon. You could help with making a pull request.

**Comment by Sentoki** [comment] 2016-07-12 02:46
Yep, same problem.

**Comment by cebe** [comment] 2016-11-22 11:32
duplicate of #8

**Closed by cebe** 2016-11-22 11:32 UTC
