### ISSUE TITLE
[ask] Null Coalesce Operator

### ISSUE THREAD

**Issue by arturf** [yiisoft/yii2-apidoc#71] opened 2016-06-13 15:18 UTC
Extension throws an error when code use `??` operator. 

Seems that compatibility with php7 fixed in new versions of dependencies (https://github.com/nikic/php-parser#php-parser), But I think that simple update may cause additional issues and needs more deeper testing... Maybe exist some workaround for this?

Thanks. 

And trace: 

```
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
45 files to update.
Processing files... 77% (35/45) ETA: n/a   PHP Notice 'yii\base\ErrorException' with message 'Undefined offset: 282'

in PATH/vendor/nikic/php-parser/lib/PHPParser/Lexer.php:121

Stack trace:
#0 PATH/vendor/nikic/php-parser/lib/PHPParser/Lexer.php(121): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/home/artur/_re...', 121, Array)
#1 PATH/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Lexer.php(48): PHPParser_Lexer->getNextToken('??', Array, Array)
#2 PATH/vendor/nikic/php-parser/lib/PHPParser/Parser.php(979): phpDocumentor\Reflection\Lexer->getNextToken('??', Array, Array)
#3 PATH/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Traverser.php(52): PHPParser_Parser->parse('<?php\nnamespace...')
#4 PATH/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/FileReflector.php(163): phpDocumentor\Reflection\Traverser->traverse('<?php\nnamespace...')
#5 PATH/vendor/yiisoft/yii2-apidoc/models/Context.php(67): phpDocumentor\Reflection\FileReflector->process()
#6 PATH/vendor/yiisoft/yii2-apidoc/commands/ApiController.php(99): yii\apidoc\models\Context->addFile('app/api/common/...')
#7 [internal function]: yii\apidoc\commands\ApiController->actionIndex(Array, './guide')
#8 PATH/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#9 PATH/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#10 PATH/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('', Array)
#11 PATH/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('', Array)
#12 PATH/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('api', Array)
#13 PATH/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('api', Array)
#14 PATH/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 PATH/vendor/yiisoft/yii2-apidoc/apidoc(53): yii\base\Application->run()
#16 {main}
```

**Comment by cebe** [comment] 2016-11-22 12:17
duplicate of #8

**Closed by cebe** 2016-11-22 12:17 UTC
Labels: bug, php 7
