### ISSUE TITLE
It doesn't work with PHP 7.2

### ISSUE THREAD

**Issue by ricpelo** [yiisoft/yii2-apidoc#163] opened 2018-02-26 16:39 UTC
### What steps will reproduce the problem?

```sh
$ composer create-project --prefer-dist yiisoft/yii2-app-basic basic
$ cd basic
$ vi composer.json (require "yiisoft/yii2-apidoc": "dev-master")
$ composer update
$ vendor/bin/apidoc api .,vendor/yiisoft/yii2 docs/api \
        --pageTitle="API del proyecto" --guide=.. --guidePrefix= \
        --exclude="docs,vendor,tests" --interactive=0
```

### What's expected?

Documentation generated OK.

### What do you get instead?

```
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
438 files to update.
Processing files... 14% (64/438) ETA: 34 sec.   PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in vendor/yiisoft/yii2/base/Object.php on line 28
Error: The given file could not be interpreted as it contains errors: 
Fatal error: Cannot use 'Object' as class name as it is reserved in vendor/yiisoft/yii2/base/Object.php on line 28

Errors parsing vendor/yiisoft/yii2/base/Object.php
```

### Additional info

- I'm using the latest HEAD from `yii2-apidoc`, including commit dbc640a.
- Using PHP 7.1 it works OK.

| Q                  | A
| ------------------ | ---
| Yii vesion         | 2.0.14.1
| Yii APIDoc version | dev-master
| PHP version        | 7.2.2-3+ubuntu16.04.1+deb.sury.org+1
| Operating system   | Ubuntu 16.04.3 LTS

**Comment by ricpelo** [comment] 2018-03-01 10:53
`yii2-apidoc` HEAD requires `"phpdocumentor/reflection": "^3.0.1"` and `"nikic/php-parser": "^1.0"`, but the latter is not compatible with PHP 7.2. The first `php-parser` version which is PHP 7.2 compatible is [3.1.0](https://github.com/nikic/PHP-Parser/releases/tag/v3.1.0).

**Comment by Icedroid** [comment] 2018-07-03 10:19
I meet the same problem, how to solve it?

**Comment by ricpelo** [comment] 2018-11-07 15:34
The latest `phpdocumentor/reflection` is now [4.0.0-alpha5](https://github.com/phpDocumentor/Reflection/releases/tag/4.0.0-alpha5). Perhaps it's now a great moment for test `yii2-apidoc` with the new release.

**Comment by nadar** [comment] 2018-12-03 09:40
@ricpelo i do have the same problem. This could also be a problem cause https://github.com/yiisoft/yii2/blob/master/framework/base/Object.php is still in the vendor folder, but i have no idea why its "requested" (api docs try to open/create the class).

```
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in vendor/yiisoft/yii2/base/Object.php on line 28
Error: The given file could not be interpreted as it contains errors: Errors parsing vendor/yiisoft/yii2/base/Object.php
```

**Comment by nadar** [comment] 2019-01-03 10:59
nadar@z270:~$ cd /var/www/luya.io/vendor/yiisoft/yii2/base/
nadar@z270:/var/www/luya.io/vendor/yiisoft/yii2/base$ rm -f Object.php 

Maybe the most stupid solution, but removing the Object.php file from vendor works for me.

**Comment by neoacevedo** [comment] 2019-03-02 17:09
I think this issue should be closed. The real solution is to have Yii2 updated to latest version.

**Comment by ricpelo** [comment] 2019-03-02 18:29
@neoacevedo It has nothing to do with the Yii2 version. Using the latest Yii2 version `2.0.16.1` and the latest HEAD from `yii2-apidoc`, I still get the following:

```
$ vendor/bin/apidoc api .,vendor/yiisoft/yii2 output
Searching files to process... done.
Loading apidoc data from cache... done.
Checking for updated files... done.
432 files to update.
Processing files... 10% (46/432) ETA: n/a   PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in vendor/yiisoft/yii2/base/Object.php on line 28
Error: The given file could not be interpreted as it contains errors: 
Fatal error: Cannot use 'Object' as class name as it is reserved in vendor/yiisoft/yii2/base/Object.php on line 28
Errors parsing vendor/yiisoft/yii2/base/Object.php
```

```
$ composer show | grep "yiisoft/yii2 \|yiisoft/yii2-apidoc"
yiisoft/yii2                       2.0.16.1           Yii PHP Framework Version 2
yiisoft/yii2-apidoc                dev-master 7f08120 API Documentation generator for the Yii framework 2.0
```

```
$ php -v
PHP 7.3.2-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 15:43:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2-3+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by neoacevedo** [comment] 2019-03-02 19:47
@ricpelo de acuerdo a como está ejecutando el comando _apidoc_, está generando la documentación para el framework de yii2:
> vendor/bin/apidoc api .,vendor/yiisoft/yii2

Yii2 aún mantiene este archivo: https://github.com/yiisoft/yii2/blob/master/framework/base/Object.php 
pero esta clase está marcada como obsoleta. El error no es de esta extensión, es del framework en sí. Ya realicé una sugerencia para remover el archivo del repositorio.

**Comment by ricpelo** [comment] 2019-03-03 08:24
@neoacevedo La clase `Object` sólo está obsoleta desde PHP 7.2, pero Yii 2 debe mantener la retrocompatibilidad con PHP 5.4. Supongo que por eso no se podrá borrar ese archivo en Yii 2 y habrá que esperar a Yii 3 para hacerlo.

**Comment by neoacevedo** [comment] 2019-03-03 19:08
Desde yii 2.0.13 fue marcada como obsoleta por la entrada de PHP 7.1.

Ahora, debería revisar si alguna de las clases creadas en su código heredan
de Object de yii2, en cuyo caso diría que reemplazara esa herencia por
BaseObject lo cual dejaría de llamar la clase de yii2 Object. Lo otro es si
necesita generar la documentación del framework que es como veo que está
usando yii2-apidoc. Para este caso sí no sabría cómo resolver esa
dependencia.



Néstor Acevedo on about.me

Néstor Acevedo
about.me/nacevedo

**Comment by My6UoT9** [comment] 2019-05-24 08:59
--exclude="......,base/Object.php"
Just exclude Object.php

**Comment by ricpelo** [comment] 2019-05-24 10:11
> @My6UoT9 
> --exclude="......,base/Object.php"
> Just exclude Object.php

```
vendor/bin/apidoc api .,vendor/yiisoft/yii2 docs/api \                                                    
    --guide=.. --guidePrefix= \
    --exclude="docs,vendor,tests,vendor/yiisoft/yii2/base/Object.php" \
    --interactive=0
```

it doesn't work because putting `vendor/yiisoft/yii2` in the first line has preference over `--exclude` option.

**Comment by My6UoT9** [comment] 2019-05-24 10:29
`set YII_PATH=%~dp0
set OUTPUT=docs
.\vendor\bin\apidoc api %YII_PATH%\vendor\yiisoft\yii2,%YII_PATH% %OUTPUT%\api --guide=..\ --guidePrefix= --interactive=0 --exclude="yii2docs,environments,vagrant,vendor,base/Object.php"
`
That is the command line I use, its for windows though

**Comment by My6UoT9** [comment] 2019-05-28 14:11
FYI I just ported my batch to composer scripts, and for unknown reasons it did not work anymore.
I tried full path, partial path - didnt work, so ended up with "Object.php", tested on windows.

```

    "scripts": {
        "docs": [
            "apidoc api ./vendor/yiisoft/yii2,. backend/web/docs --guide=../ --guidePrefix= --interactive=0 --exclude=\"yii2docs,environments,vagrant,vendor,Object.php\"",
            "apidoc guide ./vendor/yiisoft/yii2,. backend/web/docs --guidePrefix=  --interactive=0"
        ]
    }
```

**Comment by samdark** [comment] 2019-08-20 23:25
See #146

**Comment by samdark** [comment] 2020-07-19 23:03
Solved in current master.

**Comment by ricpelo** [comment] 2020-09-18 20:24
Sorry, but I can still reproduce the issue:

```sh
$ composer create-project --prefer-dist yiisoft/yii2-app-basic basic
$ cd basic
$ vi composer.json (require "yiisoft/yii2-apidoc": "dev-master")
$ composer update
$ vendor/bin/apidoc api .,vendor/yiisoft/yii2 docs/api \
        --pageTitle="API del proyecto" --guide=.. --guidePrefix= \
        --exclude="docs,vendor,tests" --interactive=0

Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
441 files to update.
Processing files... 33% (147/441) ETA: 12 sec.   PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in vendor/yiisoft/yii2/base/Object.php on line 28
Processing files... done.
Updating cross references and backlinks... done.
Rendering files: done.
generating extension index files...done.
generating search index...done.
1278 errors have been logged to docs/api/errors.txt
106 warnings have been logged to docs/api/warnings.txt
```

**Comment by nadar** [comment] 2020-09-19 06:14
Unless the Object.php file exists this error while always thrown, we have the same problem. A solution could be to blacklist this file by default.

**Comment by bizley** [comment] 2020-09-19 08:27
Hmm, wait - this is the question:
If there is `Object` the app won't work anyway so is there a need to patch apidocs to work with code that is erroneous?

**Comment by samdark** [comment] 2020-09-19 12:30
@bizley no, the app will work. The issue is about a class that isn't used anywhere:

> Processing files... 33% (147/441) ETA: 12 sec.   PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in vendor/yiisoft/yii2/base/Object.php on line 28

**Comment by bizley** [comment] 2020-09-19 18:55
Ahh, right, I forgot we keep the `Object` for BC...

**Comment by bizley** [comment] 2020-09-19 18:56
@nadar idea sounds good

**Comment by bizley** [comment] 2020-09-20 10:25
I've started to work on the fix but is it actually needed? As I see docs are generated properly.

- Exception is thrown but it's caught.
- Problematic file is skipped.

All "bad" that is happening is error text being displayed. We could hide it by pre-checking the files for reserved class names but it would require doing basically the same thing that `FileReflector` is doing already (you cannot depend on the file name itself).

I would vote to close that issue.

**Comment by samdark** [comment] 2020-09-20 10:27
Ah, right. I forgot that I've added try-catch there. I agree about closing the issue.

**Closed by samdark** 2020-09-20 10:27 UTC
Labels: help wanted, php7, status:ready for adoption, type:bug
