### ISSUE TITLE
nikic/php-parser 1.* is toooooold

### ISSUE THREAD

**Issue by shushenghong** [yiisoft/yii2-apidoc#182] opened 2019-11-02 01:49 UTC
phpDocumentor/Reflection and nikic/php-parser is too old.
this may cause class missing and any other problems, since php-parser 1.* is 4 years ago and only support php5.
need upgrade the composer and maybe the code :)

**Comment by samdark** [comment] 2019-11-02 08:46
Duplicate of #146. If you want to work on it, feel free to do so.

**Closed by samdark** 2019-11-02 08:46 UTC
